### ISSUE TITLE
did:ipid:QmYA7p467t4BGgBL4NmyHtsXMoPrYH9b3kSG6dbgFYskJm is not resolvable

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/universal-resolver#79] opened 2020-02-08 19:22 UTC

**Comment by peacekeeper** [comment] 2021-06-30 17:45
We looked at this on the [30 Jun 2021 Universal Resolver call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls), and confirmed that this DID doesn't seem to be resolvable (probably because the underlying IPFS data is lost).

@jonnycrunch what is the status of `did:ipid`, any plans to continue to maintain it? Do you have a sample DID that should work?

**Comment by peacekeeper** [comment] 2021-10-06 12:07
We looked at this again on the [06 Oct 2021 Universal Resolver Work Item Call](https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#special-work-item-calls) and decided to close this.

@jonnycrunch we would still be interested in a working `did:ipid` example, if you have one!

**Closed by peacekeeper** 2021-10-06 12:07 UTC
